theme = "solarized-dark"
icons = "awesome"

[[block]]
block = "net"
device = "wlp4s0"
ssid = true
ip = true
speed_up = false
speed_down = false
#graph_up = true
interval = 3

[[block]]
block = "net"
device = "enx00e04c6807d9"
ssid = true
ip = true
speed_up = false
speed_down = false
#graph_up = true
interval = 3

#[[block]]
#block = "temperature"
#collapsed = false
#interval = 10
#format = "{min}° min, {max}° max, {average}° avg"

[[block]]
block = "music"
max_width = 21
marquee = false
player = "spotify"
buttons = ["prev", "play", "next"]

#[[block]]
#block = "bluetooth"
#mac = "38:18:4C:3B:D1:A6"

#[[block]]
#block = "load"
#interval = 1
#format = "{1m}"

[[block]]
block = "cpu"
interval = 1

[[block]]
block = "memory"
interval = 5
info_type = "memory"
format_mem = "{Mup}%"
format_swap = "{SUp}%"

[[block]]
block = "disk_space"
path = "/"
#alias = "disc:"
info_type = "available"
unit = "GB"
interval = 20

[[block]]
block = "battery"

[[block]]
block = "sound"

[[block]]
block = "xrandr"
icons = true

[[block]]
block = "time"
interval = 60
format = "%a %d.%m.%Y %R"

#[[block]]
#block = "custom"
#interval = 999999
#command = "echo '\uF011'"
#on_click = "i3-nagbar -t warning -m 'What do you want to do?' -b 'Shutdown' 'shutdown now' -b 'Hibernate' 'systemctl hibernate' -b 'Reboot' 'reboot'"
